version: '3.8'

services:
  coupon-api:
    build: .
    container_name: coupon-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always

  coupon-frontend:
    build: 
      context: .
      dockerfile: FrontEND/Dockerfile
    container_name: coupon-frontend
    ports:
      - "80:80"
    depends_on:
      - coupon-api
    restart: always
